# Generated by Django 5.0.7 on 2024-07-31 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0004_servicoadicional_servico_servicos_adicionais'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='categoria_manutencao',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='servicos_adicionais',
        ),
        migrations.AddField(
            model_name='servico',
            name='categoria',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.DeleteModel(
            name='CategoriaManutencao',
        ),
        migrations.DeleteModel(
            name='ServicoAdicional',
        ),
    ]
