# Generated by Django 5.0.7 on 2024-07-28 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='ano',
            new_name='idade',
        ),
        migrations.AddField(
            model_name='pet',
            name='raca',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
