# Generated by Django 5.0.7 on 2024-07-31 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_rename_ano_pet_idade_pet_raca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=15),
        ),
    ]
