# Generated by Django 5.0.7 on 2024-07-31 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_cliente_cpf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='cirurgias',
            new_name='banhos',
        ),
        migrations.AddField(
            model_name='pet',
            name='tosas',
            field=models.IntegerField(default=0),
        ),
    ]
